//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarsInSalon
    {
        public string CarName
        {
            get
            {
                return Cars.Marks.Name + " " + Cars.Model;
            }
        }

        public long CIS_Id { get; set; }
        public Nullable<int> Car { get; set; }
        public Nullable<int> Salon { get; set; }
        public Nullable<long> Price { get; set; }
        public Nullable<byte> Count { get; set; }
    
        public virtual Cars Cars { get; set; }
        public virtual Salons Salons { get; set; }
    }
}
