//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.DataBase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SalonDirectoryEntities : DbContext
    {
        public SalonDirectoryEntities()
            : base("name=SalonDirectoryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cars> Cars { get; set; }
        public virtual DbSet<CarsInSalon> CarsInSalon { get; set; }
        public virtual DbSet<Marks> Marks { get; set; }
        public virtual DbSet<Salons> Salons { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
